- name: Copying the redis.repo
  ansible.builtin.copy:
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo

- name: Install Redis
  ansible.builtin.package: 
   name: redis-6.2.11
   state: present

- name: Updating the {{COMPONENT}} config
  ansible.builtin.replace:
    path: /etc/{{COMPONENT}}/{{COMPONENT}}.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  notify: Restarting {{COMPONENT}} service

- name: Restarting {{COMPONENT}} service
  ansible.builtin.service:
    name: "{{COMPONENT}}"
    state: started
    enabled: true

