- name: to check the uptime
  hosts: all
  tasks: 
  - name: Execute the shell command
    ansible.builtin.shell: uptime
    register: OUT
  
  - name: Print a variable
    ansible.builtin.debug:
     msg: "{{OUT.stdout}}" 
  