- name: to check the uptime
  hosts: all
  tasks: 
  - name: Execute the shell command
    ansible.builtin.shell: uptime
    register: OUT
  
  - name: Print a variable
    ansible.builtin.debug:
     msg: "{{OUT.stdout}}" 
  
  - name: Daclaring the variable
    ansible.builtin.set_fact:
     STATUS: "{{OUT.rc}}"
  
  - name: Printing the EXIT CODE
    ansible.builtin.debug:
     msg: "{{STATUS}}"
 
  