- name: Demo on priviledge escalation
  hosts: all
  become: yes
  tasks:
   - name: Executing shell command
     ansible.builtin.shell: id
     register: OUT

   - name: Displaying outpu
     ansible.builtin.debug:
      msg: "{{OUT}.stdout}"