- name: Demo on priviledge escalation
  hosts: all
  tasks:
   - name: PRinting a loop
     ansible.builtin.debug:
      msg: Value of Loop is "{{item}}"
     loop:
      - 10
      - 20
      - 30
      - 40
      - 50
